[workspace]
members = [
	"frame/evm/precompile/call-vm",
	"frame/vm-bridge",
	"frame/rgrandpa",
	"frame/esbind",
	"node",
	"runtime/cycan",
]
exclude = [
	"vendor",
]

[profile.release]
panic = "unwind"

